version: "3.3"

services:
  geoserver:
    image: abhinaypodugu151/geoserver
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: geoserver_data
        target: /usr/share/geoserver/data_dir

  webapp:
    image: abhinaypodugu151/webapp
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grass
        target: /usr/src/app/oct/grass
      - type: volume
        source: output
        target: /usr/src/app/oct/output
      - type: volume
        source: geoserver_data
        target: /usr/share/geoserver/data_dir
    environment:
      - DATA_FROM_BROWSER_DIR=/usr/src/app/oct/data_from_browser
      - GRASS_DIR=/usr/src/app/oct/grass
      - OUTPUT_DIR=/usr/src/app/oct/output
      - GEOSERVER_URL=http://glorious-eureka-x6gxp6xj7wgfp5qx-8080.app.github.dev/
      - INITIAL_LAT=20.264444444444
      - INITIAL_LON=85.828055555556
      - USE_LANG=

volumes:
  geoserver_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./geoserver_data_dir
  grass:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grass
  output:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./output
